. ${HOME}/etc/bash.d/aliases
. ${HOME}/etc/bash.d/extra

# Start X11 if on tty1
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    startx
    sudo netctl start wlp3s0PitucaPlus
    sudo systemctl stop dhcpcd
fi
