#!/bin/sh

# special thanks to https://unix.stackexchange.com/questions/89571/how-to-get-volume-level-from-the-command-line
notify-send "Volume level" "$(amixer sget Master | awk -F "[][]" '/dB/ { print $2 }')"
