#! /bin/sh

xrdb ${HOME}/etc/xorg.d/colors/moonbow
xsetroot -solid '#808080'
compton --config $HOME/etc/config.d/compton/compton.conf &

bspc monitor -d I II III IV V

##########################
#
# Configs
#
##########################

bspc config border_width         3
bspc config window_gap           6

#bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true

bspc config normal_border_color "#393638"
bspc config active_border_color "#817267"
bspc config focused_border_color "#97a293"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# set alt as pointer modifier
bspc config pointer_modifier mod4

# i miss windowchef
bspc config pointer_action1 move
bspc config pointer_action3 resize_corner
##########################
#
# Rules
#
##########################

bspc rule -a Gimp state=floating follow=on border=off
bspc rule -a qutebrowser desktop='2' border=off
bspc rule -a feh floating=on manage=off border=off
bspc rule -a Emacs state=tiled border=off
bspc rule -a zathura state=tiled floating=off border=off
bspc rule -a polybar sticky=on

$HOME/etc/config.d/polybar/launch.sh
