#! /bin/sh

sxhkd &
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

##########################
#
# Configs
#
##########################

bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

##########################
#
# Rules
#
##########################

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Discord desktop='^3'
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a feh floating=on manage=off
