#! /bin/sh

#polybar -c /home/arskiy/.config/polybar/config top &
sh /home/arskiy/.bing.sh

bspc monitor -d I II III IV V VI

##########################
#
# Configs
#
##########################

bspc config border_width         1
bspc config window_gap           6

#bspc config split_ratio         0.50
#bspc config borderless_monocle  true
#bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# set alt as pointer modifier
bspc config pointer_modifier mod1

bspc config pointer_action3 move
bspc config pointer_action1 resize_corner
##########################
#
# Rules
#
##########################

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qutebrowser desktop='2'
bspc rule -a Discord desktop='1'
bspc rule -a Spotify desktop='5' pseudo_tiled=on
bspc rule -a feh floating=on manage=off
bspc rule -a Emacs state=tiled
