#!/usr/bin/env bash

TMP_AVI=$(mktemp  /tmp/$USER.XXXXXXXXX.avi)
DEST="/home/arskiy/Files/gifs/$(date +%m:%d::%T.gif)"

PALETTE="/home/arskiy/Files/gifs/palette.$$.png"

DURATION=$(seq 1 70 | awk 'NR % 5 == 0' | rofi -dmenu -i -p "> " -theme ~/.config/rofi/onedark.rasi)

ffcast -s % ffmpeg -y -f x11grab -show_region 1 -framerate 15 \
        -video_size %s -i %D+%c -codec:v huffyuv \
        -t $DURATION \
        -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)" $TMP_AVI \
&& ffmpeg -y -i $TMP_AVI -vf palettegen $PALETTE \
&& ffmpeg -y -i $TMP_AVI -ss 0 -t $DURATION -i $PALETTE -filter_complex paletteuse -r 10 $DEST \
&& notify-send "rofrecord" "Gif saved."

rm $TMP_AVI $PALETTE
