#!/usr/bin/env bash

TMP_AVI=$(mktemp  /tmp/$USER.XXXXXXXXX.avi)
DEST_DIR=$(mktemp ~/Files/gifs/XXXXXXXXX.gif)

DURATION=$(seq 1 60 | awk 'NR % 5 == 0' | rofi -dmenu)
ffcast -s % ffmpeg -y -f x11grab -show_region 1 -framerate 15 \
        -video_size %s -i %D+%c -codec:v huffyuv \
        -t $DURATION \
        -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)" $TMP_AVI \
&& ffmpeg -ss 0 -t $DURATION -i $TMP_AVI $DEST_DIR \
&& notify-send "rofrecord" "Gif saved."

rm $TMP_AVI $DEST_DIR
