#!/bin/sh

LOCK="/home/arskiy/.local/share/colemak.lck"

if [ -f $LOCK ]; then
    setxkbmap -layout us -variant intl -option ctrl:nocaps
    rm $LOCK
else
    setxkbmap us -variant colemak -option ctrl:nocaps
    touch $LOCK
fi
